
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234

# ???? ??
#  mvc:
#    view:
#      prefix: /templates/
#      suffix: .mustache

  jpa:
    hibernate:
      # ????
      # update? ?? ?? ??? ???? ??
      # create? ?? drop? ?? ?? ???? ???
      ddl-auto: update  #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          # provider
          google:
              client-id: 871056400007-liaqia5mvoaljrt00okf8jt5js0a9151.apps.googleusercontent.com
              client-secret: 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
              scope:
              - email
              - profile

          # non provider
          naver:
            client-id: zpoMwzvp2LNNtPn5gRsM
            client-secret: SkOG3WqJyg
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code # code or credential
            redirect-uri: http://localhost:8080/login/oauth2/code/naver


          kakao:
            client-id: 0cda10e114af88a93a17b774ffd07357
            client-secret: QfzWVNfPMDhZVWOiJJFv1fEGpXfsj51Q
            scope:
              - profile_nickname
              - account_email
            client-name: Kakao
            authorization-grant-type: authorization_code # code or credential
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: client_secret_post

        provider: # enroll new provider
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize # login page
            token-uri: https://nid.naver.com/oauth2.0/token # get token
            user-info-uri: https://openapi.naver.com/v1/nid/me # get client's info
            user-name-attribute: response # get client's info by json with response as key

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id